import PageHeader from "../../components/PageHeader";
import { Shield, Lock, Eye, Database, UserCheck, Mail } from "lucide-react";

const SECTIONS = [
  {
    icon: Database,
    title: "1. Information We Collect",
    body: [
      "Identification details you provide during onboarding (name, address, mobile, email, KYC documents).",
      "Service usage metadata (session logs, bandwidth utilisation, package activity) generated by our network equipment.",
      "Payment information processed via CCAvenue — we do not store card numbers, CVV or UPI PIN on our servers.",
      "Technical data such as MAC addresses, allocated IP, ONT/router identifiers required for connectivity.",
    ],
  },
  {
    icon: Eye,
    title: "2. How We Use Your Information",
    body: [
      "Provisioning, activating and maintaining your internet service.",
      "Generating invoices, receipts and account statements as mandated by the Companies Act & GST laws.",
      "Responding to support tickets, complaints and queries raised through any channel (portal, phone, WhatsApp).",
      "Complying with lawful directions from TRAI, DoT, MHA and other regulatory / law-enforcement authorities.",
      "Improving product quality — with anonymised, aggregate telemetry only.",
    ],
  },
  {
    icon: Lock,
    title: "3. How We Protect Your Data",
    body: [
      "All authentication traffic between your device and our portals is encrypted with TLS 1.2+.",
      "Passwords are hashed one-way with industry-standard algorithms — plaintext is never stored.",
      "Access to subscriber data is role-based; only authorised staff on active tickets can view your account.",
      "Backups are encrypted at rest and retained per our data-retention policy (below).",
    ],
  },
  {
    icon: UserCheck,
    title: "4. Sharing & Disclosure",
    body: [
      "We do NOT sell subscriber data. Ever.",
      "We share data only: (a) with regulators on lawful demand, (b) with our payment gateway (CCAvenue) to process transactions, (c) with hardware vendors when RMA / warranty support is required.",
      "Marketing communication is opt-in — unsubscribe links are always provided.",
    ],
  },
  {
    icon: Shield,
    title: "5. Retention & Deletion",
    body: [
      "Billing records and invoices: retained for 8 years as required by GST / Income-Tax rules.",
      "Session logs: retained for 180 days (or as directed by DoT for License-Category-specific requirements).",
      "You may request deletion of your marketing profile by writing to contact@insightnet.in.",
    ],
  },
  {
    icon: Mail,
    title: "6. Your Rights",
    body: [
      "Right to access — request a copy of the data we hold on you.",
      "Right to rectification — correct any inaccurate personal information via the subscriber portal or ticket.",
      "Right to withdraw consent for non-mandatory processing.",
      "Right to lodge a complaint with the appointed Grievance Officer within 30 days.",
    ],
  },
];

export default function Privacy() {
  return (
    <div data-testid="privacy-page">
      <PageHeader
        eyebrow="LEGAL"
        title="Privacy"
        accent="Policy"
        subtitle="How Insight Networks collects, uses and safeguards your information — written in plain language, updated 01 January 2026."
        backgroundImage="https://images.unsplash.com/photo-1550751827-4bd374c3f58b?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA2MjJ8MHwxfHNlYXJjaHwxfHxjeWJlcnNlY3VyaXR5JTIwbG9ja3xlbnwwfHx8Ymx1ZXwxNzY3MjMxMzg2fDA&ixlib=rb-4.1.0&q=85"
      />

      <section className="container mx-auto px-6 lg:px-8 py-16 max-w-5xl">
        <div className="prose prose-slate max-w-none mb-12">
          <p className="text-lg text-slate-700 leading-relaxed">
            Insight Networks (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) is an Internet Service Provider licensed to operate in India.
            This Privacy Policy describes what personal information we collect from you as a subscriber or website
            visitor, why we collect it, how we use it, and the choices you have about it. By using our services or
            website, you agree to the practices described here.
          </p>
        </div>

        <div className="space-y-8">
          {SECTIONS.map((s) => {
            const Icon = s.icon;
            return (
              <div
                key={s.title}
                data-testid={`privacy-section-${s.title.replace(/\s+/g, "-").toLowerCase()}`}
                className="bg-white border-2 border-slate-200 rounded-2xl p-6 lg:p-8 shadow-sm hover:shadow-md hover:border-[#1E88FF]/40 transition-all"
              >
                <div className="flex items-start gap-5">
                  <div className="w-12 h-12 rounded-xl bg-blue-50 flex items-center justify-center shrink-0">
                    <Icon className="text-[#1E88FF]" size={24} />
                  </div>
                  <div className="flex-1">
                    <h2 className="font-display text-xl font-bold text-[#0A1A33] mb-4">{s.title}</h2>
                    <ul className="space-y-2.5">
                      {s.body.map((line, i) => (
                        <li key={i} className="flex items-start gap-2.5 text-slate-700">
                          <span className="w-1.5 h-1.5 rounded-full bg-[#1E88FF] mt-2 shrink-0" />
                          <span>{line}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* Grievance Officer contact */}
        <div className="mt-12 bg-gradient-to-br from-[#0A1A33] to-[#0F2847] text-white rounded-2xl p-8 lg:p-10">
          <h3 className="font-display text-2xl font-bold mb-3">Grievance Officer</h3>
          <p className="text-slate-300 leading-relaxed mb-6 max-w-2xl">
            In accordance with the IT Act 2000 and the Consumer Protection (E-Commerce) Rules 2020, the following
            officer has been appointed to receive privacy-related grievances:
          </p>
          <div className="grid sm:grid-cols-2 gap-6 text-sm">
            <div>
              <p className="text-slate-400">Name</p>
              <p className="font-semibold text-lg">Amit Khare</p>
            </div>
            <div>
              <p className="text-slate-400">Email</p>
              <a href="mailto:grievance@insightnet.in" className="font-semibold text-lg text-[#1E88FF] hover:underline">grievance@insightnet.in</a>
            </div>
            <div>
              <p className="text-slate-400">Phone</p>
              <a href="tel:+919302452424" className="font-semibold text-lg hover:text-[#1E88FF]">+91 93024 52424</a>
            </div>
            <div>
              <p className="text-slate-400">Response TAT</p>
              <p className="font-semibold text-lg">Within 30 days of receipt</p>
            </div>
          </div>
        </div>

        <p className="text-xs text-slate-500 text-center mt-10">
          Effective date: 01 January 2026 &middot; Last updated: 01 January 2026
        </p>
      </section>
    </div>
  );
}
